apiVersion: v1
kind: Namespace
metadata:
  name: bubble-dev
---
apiVersion: v1
kind: Secret
metadata:
  name: database-auth
  namespace: bubble-dev
  labels:
    app: bubble-backend
type: Opaque
stringData:
  POSTGRES_HOST: "bubble-database-service"
  POSTGRES_DB: "bubble_penetration"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"