apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'

android {
    namespace 'de.spicysources.bubblepenetration'
    compileSdk 34

    defaultConfig {
        applicationId "de.spicysources.bubblepenetration"
        minSdk 14
        targetSdk 34
        versionCode 5
        versionName "1.1"

        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }


    signingConfigs {
        release {
            storeFile file("keystores/bp-release-keystore.jks")
            storePassword "bp-release"
            keyAlias "ss-keystore"
            keyPassword "bp-release"
        }
    }

    buildTypes {
        debug {
            buildConfigField "String", "BACKEND_BASEURL", "\"${project.findProperty("backendUrl") ?: "https://dev.bubble.lukas-scheerer.de/api"}\""
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
            buildConfigField "String", "BACKEND_BASEURL", "\"${project.findProperty("backendUrl") ?: "https://bubble.lukas-scheerer.de/api"}\""
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    
    kotlinOptions {
        jvmTarget = '1.8'
    }

    buildFeatures {
        buildConfig = true
    }
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
}