plugins {
    id 'org.jetbrains.kotlin.multiplatform'
    id 'com.android.kotlin.multiplatform.library'
}

kotlin {
    android {
        namespace = 'org.codeberg.scovillo.bubble.core'
        compileSdk = 37
        minSdk = 14
        withHostTest {}
    }
    jvm()

    sourceSets {
        commonMain {
            dependencies {
            }
        }
        commonTest {
            dependencies {
                implementation kotlin('test')
            }
        }
    }
}
