import {
  DeterministicGenerator,
  ReplayValidationError,
  ReplayValidator,
} from './replay-validator';

describe('Seeded replay validation', () => {
  const seed = '0123456789abcdef'.repeat(4);
  const validator = (
    events: Array<{
      objectId: string;
      timestampMs: number;
      x: number;
      y: number;
    }>,
    declaredScore: number,
    declaredDurationMs: number,
  ) =>
    new ReplayValidator(
      seed,
      {
        events,
        declaredScore,
        declaredDurationMs,
        viewportAspectRatio: 1,
      },
      { playerId: 'test-player', sessionId: 'test-session' },
    );

  it('generates stable objects tied to the seed', () => {
    const first = new DeterministicGenerator(seed).objectAt(17, 42);
    const second = new DeterministicGenerator(seed).objectAt(17, 42);
    const otherSeed = new DeterministicGenerator('ff'.repeat(32)).objectAt(
      17,
      42,
    );

    expect(first).toEqual(second);
    expect(first.id).not.toBe(otherSeed.id);
  });

  it('makes a generated bubble collectable when no target bubble is alive', () => {
    const generator = new DeterministicGenerator(seed);
    let index = 0;
    let object = generator.objectAt(index, 0);
    while (object.kind !== 'bubble' || object.color === 'red') {
      index += 1;
      object = generator.objectAt(index, 0);
    }

    expect(generator.objectForField(index, 0, 1, 'red', false).color).toBe(
      'red',
    );
    expect(generator.objectForField(index, 0, 1, 'red', true).color).toBe(
      object.color,
    );
  });

  it('turns a star into the required target when no target bubble is alive', () => {
    const generator = new DeterministicGenerator(seed);
    let index = 0;
    let object = generator.objectAt(index, 0);
    while (object.kind !== 'star') {
      index += 1;
      object = generator.objectAt(index, 0);
    }

    expect(generator.objectForField(index, 0, 1, 'green', false)).toMatchObject(
      {
        kind: 'bubble',
        color: 'green',
      },
    );
  });

  it('rejects a replay that tries to hit an object beyond the 20-object field cap', () => {
    const generator = new DeterministicGenerator(seed);
    const object = generator.objectAt(20, 0);
    const timestampMs = object.spawnAtMs + 500;
    const position = generator.positionAt(object, timestampMs);
    const declaredDurationMs = 25_000;

    expect(() =>
      validator(
        [{ objectId: object.id, timestampMs, ...position }],
        0,
        declaredDurationMs,
      ).validate(),
    ).toThrow(ReplayValidationError);
  });

  it('accepts a replay with no hits when the initial timer expires', () => {
    expect(validator([], 0, 25_000).validate()).toEqual({
      score: 0,
      finishedAtMs: 25_000,
    });
  });

  it('reconstructs a concrete hit, score and resulting game time', () => {
    const generator = new DeterministicGenerator(seed);
    const object = generator.objectForField(0, 0, 1, 'red', false);

    const timestampMs = object.spawnAtMs + 500;
    const position = generator.positionAt(object, timestampMs);
    const bubbleTime = 1.25 - 0.25 * Math.log2(0.75 * object.speed + 1);
    const durationMs = Math.round(25_000 + bubbleTime * 1_000);

    expect(
      validator(
        [{ objectId: object.id, timestampMs, ...position }],
        1,
        durationMs,
      ).validate(),
    ).toEqual({ score: 1, finishedAtMs: durationMs });
  });

  it('rejects an object id not generated by the session seed', () => {
    expect(() =>
      validator(
        [
          {
            objectId: 'o_0_deadbeef',
            timestampMs: 100,
            x: 0.5,
            y: 0.5,
          },
        ],
        0,
        25_000,
      ).validate(),
    ).toThrow(ReplayValidationError);
  });

  it('rejects a score that differs from the replay', () => {
    expect(() => validator([], 1, 25_000).validate()).toThrow(
      ReplayValidationError,
    );
  });

  it('rejects a game duration that differs from the reconstructed timer', () => {
    expect(() => validator([], 0, 20_000).validate()).toThrow(
      ReplayValidationError,
    );
  });

  it('rejects a hit before the reaction window opens', () => {
    const generator = new DeterministicGenerator(seed);
    const object = generator.objectAt(0, 0);
    const timestampMs = object.spawnAtMs;

    expect(() =>
      validator(
        [
          {
            objectId: object.id,
            timestampMs,
            ...generator.positionAt(object, timestampMs),
          },
        ],
        0,
        25_000,
      ).validate(),
    ).toThrow(ReplayValidationError);
  });

  it('rejects a tap outside the reconstructed object', () => {
    const generator = new DeterministicGenerator(seed);
    const object = generator.objectAt(0, 0);

    expect(() =>
      validator(
        [
          {
            objectId: object.id,
            timestampMs: object.spawnAtMs + 200,
            x: 0.5,
            y: 0.5,
          },
        ],
        0,
        25_000,
      ).validate(),
    ).toThrow(ReplayValidationError);
  });

  it('rejects a second hit on the same object', () => {
    const generator = new DeterministicGenerator(seed);
    const object = generator.objectAt(0, 0);
    const firstTimestamp = object.spawnAtMs + 200;
    const secondTimestamp = firstTimestamp + 30;

    expect(() =>
      validator(
        [
          {
            objectId: object.id,
            timestampMs: firstTimestamp,
            ...generator.positionAt(object, firstTimestamp),
          },
          {
            objectId: object.id,
            timestampMs: secondTimestamp,
            ...generator.positionAt(object, secondTimestamp),
          },
        ],
        0,
        25_000,
      ).validate(),
    ).toThrow(ReplayValidationError);
  });
});
