const baseSections = [
  ['What we collect', '<p>Bubble Penetration does not require registration, an account, advertising or purchases. The app stores your chosen fantasy username and local high scores on your device.</p>'],
  ['Online leaderboard', '<p>When the online leaderboard is enabled, the app sends your fantasy username and score to the configured backend. The score is associated with that nickname, not with an account or real name. You can use your own compatible leaderboard or disable online play and remain offline.</p>'],
  ['Server logs and security', '<p>The backend records limited technical request information such as request time, URL, status and user-agent for operation, abuse prevention and rate limiting. We do not use this information for advertising or profiling.</p>'],
  ['Retention and deletion', '<p>Local data is deleted when you clear the app data or uninstall the app. Online scores remain in the configured leaderboard until they are removed by its operator. To request removal from the official leaderboard, contact the maintainer through the Codeberg repository.</p>'],
  ['Children and privacy', '<p>The game is designed to minimize data collection and can be played offline. Please do not enter real names, contact details or other personal information as a username.</p>'],
  ['Third-party services', '<p>The landing page links to Codeberg Releases and F-Droid. Those services process data under their own privacy policies when you visit them. The app itself contains no analytics SDK, advertising SDK or payment service.</p>'],
  ['Your rights and contact', '<p>Depending on your location, you may have rights to access, correct or erase personal data and to object to processing. The service operator is Lukas Scheerer. Contact and removal requests can be made via <a href="https://codeberg.org/scovillo/bubble-penetration">the project repository</a>.</p>']
];
const deSections = [
  ['Welche Daten wir erheben', '<p>Bubble Penetration benötigt weder Registrierung noch Benutzerkonto und enthält keine Werbung oder Käufe. Der von dir gewählte Fantasie-Benutzername und lokale Bestleistungen werden auf deinem Gerät gespeichert.</p>'],
  ['Online-Bestenliste', '<p>Wenn die Online-Bestenliste aktiviert ist, übermittelt die App deinen Fantasie-Benutzernamen und deine Punktzahl an das konfigurierte Backend. Die Punktzahl ist mit diesem Spitznamen verknüpft, nicht mit einem Konto oder deinem echten Namen. Du kannst eine eigene kompatible Bestenliste verwenden oder vollständig offline spielen.</p>'],
  ['Server-Logs und Sicherheit', '<p>Das Backend protokolliert begrenzte technische Informationen wie Zeitpunkt, URL, Status und User-Agent, um den Dienst zu betreiben, Missbrauch zu verhindern und Anfragen zu begrenzen. Diese Informationen werden nicht für Werbung oder Profile verwendet.</p>'],
  ['Speicherung und Löschung', '<p>Lokale Daten werden gelöscht, wenn du die App-Daten löschst oder die App deinstallierst. Online-Punkte bleiben in der jeweiligen Bestenliste, bis sie durch deren Betreiber entfernt werden. Für eine Löschung in der offiziellen Bestenliste kontaktiere bitte den Maintainer über das Codeberg-Repository.</p>'],
  ['Kinder und Datenschutz', '<p>Das Spiel minimiert die Datenerhebung und kann offline gespielt werden. Bitte verwende keine echten Namen, Kontaktdaten oder sonstigen persönlichen Informationen als Benutzernamen.</p>'],
  ['Drittanbieter', '<p>Die Landingpage verlinkt auf Codeberg Releases und F-Droid. Beim Besuch dieser Angebote gelten deren eigene Datenschutzbestimmungen. Die App enthält kein Analyse-, Werbe- oder Bezahlsystem.</p>'],
  ['Rechte und Kontakt', '<p>Je nach Aufenthaltsort hast du möglicherweise Rechte auf Auskunft, Berichtigung, Löschung und Widerspruch. Verantwortlich ist Lukas Scheerer. Kontakt- und Löschanfragen kannst du über <a href="https://codeberg.org/scovillo/bubble-penetration">das Projekt-Repository</a> stellen.</p>']
];
export const privacy = { en:{title:'Privacy policy',description:'How Bubble Penetration handles local usernames, optional online highscores and technical service data.',eyebrow:'Clear by design',intro:'Bubble Penetration is built for quick fun with data minimization at its core.',back:'Back to website',updated:'Last updated: 29 August 2026',sections:baseSections}, de:{title:'Datenschutzerklärung',description:'Wie Bubble Penetration lokale Benutzernamen, optionale Online-Highscores und technische Servicedaten verarbeitet.',eyebrow:'Klar und bewusst',intro:'Bubble Penetration ist für schnellen Spielspaß gemacht – mit Datensparsamkeit als Grundprinzip.',back:'Zur Webseite',updated:'Zuletzt aktualisiert: 29. August 2026',sections:deSections} };
for (const lang of ['es','fr','ja','pt-BR','ru','uk','zh-CN']) privacy[lang] = {...privacy.en};
