export const siteUrl = 'https://scovillo.codeberg.page/bubble-penetration/';

const english = {
  name: 'English', locale: 'en-US', title: 'Bubble Penetration – Fast arcade bubble game',
  description: 'Pop the right bubbles, build combos and fight for the global high score in Bubble Penetration, a free open-source Android arcade game.',
  skip: 'Skip to content', navLabel: 'Main navigation', navGame: 'The game', navScores: 'Highscores', navPlay: 'Play now', language: 'Language',
  eyebrow: 'Fast fingers. Big combos.', heroTitle: 'Burst into the high score.', heroLead: 'Pick the right colors, chain explosive combos and turn 30 frantic seconds into your next personal best.',
  download: 'Download the game', seeScores: 'See the top 10', featuresLabel: 'Game highlights', seconds: 'seconds per run', combos: 'combo potential', topPlayers: 'players on display',
  screenshotAlt: 'Bubble Penetration gameplay with colorful bubbles and stars', liveLabel: 'Live from the arena', scoreTitle: 'Global top 10', refresh: 'Refresh', currentChampion: 'Current champion', loading: 'Loading the leaderboard…', empty: 'No scores yet. Be the first champion!', error: 'The leaderboard is taking a break. Try again shortly.', points: 'pts',
  inAction: 'The game in action', showcaseTitle: 'Easy to start. Hard to stop.', shotOne: 'Bubble Penetration main menu', shotTwo: 'Bubble Penetration highscore screen', shotThree: 'Bubble Penetration settings screen',
  ready: 'Ready?', ctaTitle: 'Your name belongs at the top.', ctaText: 'Free, open source and made for quick bursts of fun.', privacy: 'Privacy', screenshotLocale: 'en'
};

export const translations = {
  en: english,
  de: {...english, name:'Deutsch', locale:'de-DE', title:'Bubble Penetration – Rasantes Arcade-Bubble-Spiel', description:'Triff die richtigen Blasen, baue Combos auf und kämpfe um den globalen Highscore in Bubble Penetration – dem kostenlosen Open-Source-Spiel für Android.', skip:'Zum Inhalt springen', navLabel:'Hauptnavigation', navGame:'Das Spiel', navScores:'Bestenliste', navPlay:'Jetzt spielen', language:'Sprache', eyebrow:'Schnelle Finger. Große Combos.', heroTitle:'Platz dich an die Spitze.', heroLead:'Triff die richtigen Farben, verbinde explosive Combos und mache aus 30 wilden Sekunden deine nächste Bestleistung.', download:'Spiel herunterladen', seeScores:'Top 10 ansehen', featuresLabel:'Spiel-Highlights', seconds:'Sekunden pro Runde', combos:'Combo-Potenzial', topPlayers:'Plätze im Ranking', screenshotAlt:'Bubble-Penetration-Spiel mit bunten Blasen und Sternen', liveLabel:'Live aus der Arena', scoreTitle:'Globale Top 10', refresh:'Aktualisieren', currentChampion:'Aktueller Champion', loading:'Bestenliste wird geladen…', empty:'Noch keine Punkte. Werde der erste Champion!', error:'Die Bestenliste macht kurz Pause. Versuch es gleich noch einmal.', points:'Pkt.', inAction:'Mitten im Spiel', showcaseTitle:'Sofort verstanden. Schwer aufzuhören.', shotOne:'Hauptmenü von Bubble Penetration', shotTwo:'Bestenliste von Bubble Penetration', shotThree:'Einstellungen von Bubble Penetration', ready:'Bereit?', ctaTitle:'Dein Name gehört nach ganz oben.', ctaText:'Kostenlos, Open Source und perfekt für eine schnelle Runde.', privacy:'Datenschutz', screenshotLocale:'de'},
  es: {...english, name:'Español', locale:'es-ES', title:'Bubble Penetration – Juego arcade rápido de burbujas', description:'Revienta las burbujas correctas, encadena combos y lucha por la mejor puntuación global en este juego arcade gratuito para Android.', skip:'Saltar al contenido', navLabel:'Navegación principal', navGame:'El juego', navScores:'Puntuaciones', navPlay:'Jugar ahora', language:'Idioma', eyebrow:'Dedos rápidos. Combos enormes.', heroTitle:'Explota hasta llegar a la cima.', heroLead:'Elige los colores correctos, encadena combos explosivos y convierte 30 segundos frenéticos en tu nuevo récord.', download:'Descargar el juego', seeScores:'Ver el top 10', featuresLabel:'Lo mejor del juego', seconds:'segundos por partida', combos:'potencial de combo', topPlayers:'jugadores destacados', liveLabel:'En directo desde la arena', scoreTitle:'Top 10 mundial', refresh:'Actualizar', currentChampion:'Campeón actual', loading:'Cargando la clasificación…', empty:'Aún no hay puntuaciones. ¡Sé el primer campeón!', error:'La clasificación está descansando. Inténtalo pronto.', points:'pts', inAction:'El juego en acción', showcaseTitle:'Fácil de empezar. Difícil de soltar.', ready:'¿Preparado?', ctaTitle:'Tu nombre merece estar arriba.', ctaText:'Gratis, de código abierto y perfecto para partidas rápidas.', privacy:'Privacidad'},
  fr: {...english, name:'Français', locale:'fr-FR', title:'Bubble Penetration – Jeu d’arcade de bulles', description:'Éclatez les bonnes bulles, enchaînez les combos et visez le meilleur score mondial dans ce jeu Android gratuit et open source.', skip:'Aller au contenu', navLabel:'Navigation principale', navGame:'Le jeu', navScores:'Scores', navPlay:'Jouer', language:'Langue', eyebrow:'Doigts rapides. Combos géants.', heroTitle:'Éclatez tout jusqu’au sommet.', heroLead:'Choisissez les bonnes couleurs, enchaînez des combos explosifs et transformez 30 secondes intenses en nouveau record.', download:'Télécharger le jeu', seeScores:'Voir le top 10', featuresLabel:'Points forts', seconds:'secondes par partie', combos:'potentiel de combo', topPlayers:'joueurs affichés', liveLabel:'En direct de l’arène', scoreTitle:'Top 10 mondial', refresh:'Actualiser', currentChampion:'Champion actuel', loading:'Chargement du classement…', empty:'Aucun score. Devenez le premier champion !', error:'Le classement fait une pause. Réessayez bientôt.', points:'pts', inAction:'Le jeu en action', showcaseTitle:'Facile à lancer. Difficile à quitter.', ready:'Prêt ?', ctaTitle:'Votre nom mérite la première place.', ctaText:'Gratuit, open source et parfait pour une partie rapide.', privacy:'Confidentialité'},
  ja: {...english, name:'日本語', locale:'ja-JP', title:'Bubble Penetration – 爽快バブルアーケードゲーム', description:'正しいバブルを狙い、コンボをつないで世界ハイスコアを目指す、無料のオープンソースAndroidゲーム。', skip:'本文へ移動', navLabel:'メインナビゲーション', navGame:'ゲーム', navScores:'ハイスコア', navPlay:'今すぐプレイ', language:'言語', eyebrow:'素早い指。大きなコンボ。', heroTitle:'弾けて、頂点へ。', heroLead:'正しい色を選び、豪快なコンボをつないで、熱い30秒を自己ベストに変えよう。', download:'ゲームをダウンロード', seeScores:'トップ10を見る', featuresLabel:'ゲームの特徴', seconds:'秒のチャレンジ', combos:'コンボの可能性', topPlayers:'ランキング表示', liveLabel:'アリーナからライブ', scoreTitle:'世界トップ10', refresh:'更新', currentChampion:'現在のチャンピオン', loading:'ランキングを読み込み中…', empty:'まだスコアがありません。最初の王者になろう！', error:'ランキングを取得できません。しばらくして再試行してください。', points:'点', inAction:'ゲームプレイ', showcaseTitle:'すぐ遊べて、やめられない。', ready:'準備はいい？', ctaTitle:'頂点に君の名前を。', ctaText:'無料・オープンソース。短時間で楽しめます。', privacy:'プライバシー'},
  'pt-BR': {...english, name:'Português (Brasil)', locale:'pt-BR', title:'Bubble Penetration – Jogo arcade rápido de bolhas', description:'Estoure as bolhas certas, faça combos e dispute a maior pontuação global neste jogo Android gratuito e de código aberto.', skip:'Ir para o conteúdo', navLabel:'Navegação principal', navGame:'O jogo', navScores:'Pontuações', navPlay:'Jogar agora', language:'Idioma', eyebrow:'Dedos rápidos. Combos enormes.', heroTitle:'Estoure tudo até o topo.', heroLead:'Escolha as cores certas, encaixe combos explosivos e transforme 30 segundos frenéticos em seu novo recorde.', download:'Baixar o jogo', seeScores:'Ver o top 10', featuresLabel:'Destaques do jogo', seconds:'segundos por rodada', combos:'potencial de combo', topPlayers:'jogadores em destaque', liveLabel:'Ao vivo da arena', scoreTitle:'Top 10 global', refresh:'Atualizar', currentChampion:'Campeão atual', loading:'Carregando o ranking…', empty:'Ainda não há pontuações. Seja o primeiro campeão!', error:'O ranking está descansando. Tente novamente em breve.', points:'pts', inAction:'O jogo em ação', showcaseTitle:'Fácil de começar. Difícil de parar.', ready:'Pronto?', ctaTitle:'Seu nome merece o topo.', ctaText:'Grátis, de código aberto e feito para diversão rápida.', privacy:'Privacidade'},
  ru: {...english, name:'Русский', locale:'ru-RU', title:'Bubble Penetration – Динамичная аркада с пузырями', description:'Лопайте нужные пузыри, собирайте комбо и боритесь за мировой рекорд в бесплатной Android-игре с открытым кодом.', skip:'Перейти к содержанию', navLabel:'Главная навигация', navGame:'Игра', navScores:'Рекорды', navPlay:'Играть', language:'Язык', eyebrow:'Быстрые пальцы. Огромные комбо.', heroTitle:'Лопай и покоряй вершину.', heroLead:'Выбирайте правильные цвета, собирайте взрывные комбо и превращайте 30 безумных секунд в новый рекорд.', download:'Скачать игру', seeScores:'Смотреть топ-10', featuresLabel:'Особенности игры', seconds:'секунд на раунд', combos:'возможности комбо', topPlayers:'игроков в рейтинге', liveLabel:'Прямо с арены', scoreTitle:'Мировой топ-10', refresh:'Обновить', currentChampion:'Текущий чемпион', loading:'Загрузка рейтинга…', empty:'Рекордов пока нет. Станьте первым чемпионом!', error:'Рейтинг временно недоступен. Попробуйте позже.', points:'очк.', inAction:'Игра в действии', showcaseTitle:'Легко начать. Трудно остановиться.', ready:'Готовы?', ctaTitle:'Ваше имя должно быть наверху.', ctaText:'Бесплатно, открыто и идеально для быстрой игры.', privacy:'Конфиденциальность'},
  uk: {...english, name:'Українська', locale:'uk-UA', title:'Bubble Penetration – Динамічна аркада з бульбашками', description:'Лускайте правильні бульбашки, складайте комбо та боріться за світовий рекорд у безкоштовній Android-грі з відкритим кодом.', skip:'Перейти до вмісту', navLabel:'Головна навігація', navGame:'Гра', navScores:'Рекорди', navPlay:'Грати', language:'Мова', eyebrow:'Швидкі пальці. Великі комбо.', heroTitle:'Лускай і підкорюй вершину.', heroLead:'Обирайте правильні кольори, складайте вибухові комбо та перетворюйте 30 шалених секунд на новий рекорд.', download:'Завантажити гру', seeScores:'Дивитися топ-10', featuresLabel:'Особливості гри', seconds:'секунд на раунд', combos:'можливості комбо', topPlayers:'гравців у рейтингу', liveLabel:'Наживо з арени', scoreTitle:'Світовий топ-10', refresh:'Оновити', currentChampion:'Поточний чемпіон', loading:'Завантаження рейтингу…', empty:'Рекордів ще немає. Станьте першим чемпіоном!', error:'Рейтинг тимчасово недоступний. Спробуйте пізніше.', points:'очк.', inAction:'Гра в дії', showcaseTitle:'Легко почати. Важко зупинитися.', ready:'Готові?', ctaTitle:'Ваше ім’я має бути нагорі.', ctaText:'Безкоштовно, відкрито та ідеально для швидкої гри.', privacy:'Конфіденційність'},
  'zh-CN': {...english, name:'简体中文', locale:'zh-CN', title:'Bubble Penetration – 快节奏泡泡街机游戏', description:'击中正确的泡泡，连续触发组合，在这款免费开源的 Android 街机游戏中争夺全球最高分。', skip:'跳到主要内容', navLabel:'主导航', navGame:'游戏', navScores:'最高分', navPlay:'立即游玩', language:'语言', eyebrow:'手速要快。连击要大。', heroTitle:'一路爆破，冲上榜首。', heroLead:'选择正确颜色，触发爆炸连击，把紧张刺激的30秒变成你的全新纪录。', download:'下载游戏', seeScores:'查看前10名', featuresLabel:'游戏亮点', seconds:'秒一局', combos:'无限连击可能', topPlayers:'榜单玩家', liveLabel:'竞技场实时数据', scoreTitle:'全球前10名', refresh:'刷新', currentChampion:'当前冠军', loading:'正在加载排行榜…', empty:'暂无分数。成为第一位冠军吧！', error:'排行榜暂时休息，请稍后重试。', points:'分', inAction:'游戏实机画面', showcaseTitle:'上手简单，根本停不下来。', ready:'准备好了吗？', ctaTitle:'榜首就差你的名字。', ctaText:'免费、开源，随时享受快节奏乐趣。', privacy:'隐私'}
};
