export const siteUrl = 'https://scovillo.codeberg.page/bubble-penetration/';

const english = {
  name: 'English', locale: 'en-US', title: 'Bubble Penetration – Fast arcade bubble game',
  description: 'Pop the right bubbles, build combos and fight for the global high score in Bubble Penetration, a free open-source Android arcade game.',
  skip: 'Skip to content', navLabel: 'Main navigation', navGame: 'The game', navScores: 'Highscores', navPlay: 'Play now', language: 'Language',
  eyebrow: 'Fast fingers. Big combos.', heroTitle: 'Burst into the high score.', heroLead: 'Collect the required color, grab golden stars and turn every frantic run into your next personal best.',
  download: 'Download game (APK)', storeLabel:'Get the game', getItOn:'Get it on', comingSoon:'Coming soon', seeScores: 'See the top 10', featuresLabel: 'Game highlights', seconds: 'maximum combo', combos: 'bonus time & score', topPlayers: 'online, custom or offline',
  screenshotAlt: 'Bubble Penetration gameplay with colorful bubbles and stars', liveLabel: 'Live from the arena', scoreTitle: 'Global top 10', refresh: 'Refresh', currentChampion: 'Current champion', loading: 'Loading the leaderboard…', empty: 'No scores yet. Be the first champion!', error: 'The leaderboard is taking a break. Try again shortly.', points: 'pts',
  howLabel:'How it works', howTitle:'Every tap changes the run.', colorTitle:'Follow the color', colorText:'Collect the currently required color to gain points and precious time.', starTitle:'Grab golden stars', starText:'Stars reward quick reactions with bonus time and extra score.', comboTitle:'Protect your streak', comboText:'Correct hits build a multiplier up to ×16. One wrong bubble costs time and resets it.',
  inAction: 'The game in action', showcaseTitle: 'Easy to start. Hard to stop.', shotOne: 'Bubble Penetration gameplay', shotTwo: 'Bubble Penetration highscore screen', shotThree: 'Bubble Penetration settings screen',
  ready: 'Ready?', ctaTitle: 'Your name belongs at the top.', ctaText: 'Free, open source and made for quick bursts of fun.', privacy: 'Privacy', screenshotLocale: 'en'
};

export const translations = {
  en: english,
  de: {...english, name:'Deutsch', locale:'de-DE', title:'Bubble Penetration – Rasantes Arcade-Bubble-Spiel', description:'Triff die richtigen Blasen, baue Combos auf und kämpfe um den globalen Highscore in Bubble Penetration – dem kostenlosen Open-Source-Spiel für Android.', skip:'Zum Inhalt springen', navLabel:'Hauptnavigation', navGame:'Das Spiel', navScores:'Bestenliste', navPlay:'Jetzt spielen', language:'Sprache', eyebrow:'Schnelle Finger. Große Combos.', heroTitle:'Platz dich an die Spitze.', heroLead:'Sammle die geforderte Farbe, schnapp dir goldene Sterne und mache jede rasante Runde zu deiner nächsten Bestleistung.', download:'Spiel herunterladen', seeScores:'Top 10 ansehen', featuresLabel:'Spiel-Highlights', seconds:'Maximale Combo', combos:'Bonuszeit & Extrapunkte', topPlayers:'Online, eigene oder offline', screenshotAlt:'Bubble-Penetration-Spiel mit bunten Blasen und Sternen', liveLabel:'Live aus der Arena', scoreTitle:'Globale Top 10', refresh:'Aktualisieren', currentChampion:'Aktueller Champion', loading:'Bestenliste wird geladen…', empty:'Noch keine Punkte. Werde der erste Champion!', error:'Die Bestenliste macht kurz Pause. Versuch es gleich noch einmal.', points:'Pkt.', inAction:'Mitten im Spiel', showcaseTitle:'Sofort verstanden. Schwer aufzuhören.', shotOne:'Spielansicht von Bubble Penetration', shotTwo:'Bestenliste von Bubble Penetration', shotThree:'Einstellungen von Bubble Penetration', ready:'Bereit?', ctaTitle:'Dein Name gehört nach ganz oben.', ctaText:'Kostenlos, Open Source und perfekt für eine schnelle Runde.', privacy:'Datenschutz', screenshotLocale:'de'},
  es: {...english, name:'Español', locale:'es-ES', title:'Bubble Penetration – Juego arcade rápido de burbujas', description:'Revienta las burbujas correctas, encadena combos y lucha por la mejor puntuación global en este juego arcade gratuito para Android.', skip:'Saltar al contenido', navLabel:'Navegación principal', navGame:'El juego', navScores:'Puntuaciones', navPlay:'Jugar ahora', language:'Idioma', eyebrow:'Dedos rápidos. Combos enormes.', heroTitle:'Explota hasta llegar a la cima.', heroLead:'Elige los colores correctos, encadena combos explosivos y convierte cada partida frenética en tu nuevo récord.', download:'Descargar el juego', seeScores:'Ver el top 10', featuresLabel:'Lo mejor del juego', seconds:'ganas o pierdes tiempo', combos:'multiplicador de combo', topPlayers:'clasificación mundial', liveLabel:'En directo desde la arena', scoreTitle:'Top 10 mundial', refresh:'Actualizar', currentChampion:'Campeón actual', loading:'Cargando la clasificación…', empty:'Aún no hay puntuaciones. ¡Sé el primer campeón!', error:'La clasificación está descansando. Inténtalo pronto.', points:'pts', inAction:'El juego en acción', showcaseTitle:'Fácil de empezar. Difícil de soltar.', ready:'¿Preparado?', ctaTitle:'Tu nombre merece estar arriba.', ctaText:'Gratis, de código abierto y perfecto para partidas rápidas.', privacy:'Privacidad'},
  fr: {...english, name:'Français', locale:'fr-FR', title:'Bubble Penetration – Jeu d’arcade de bulles', description:'Éclatez les bonnes bulles, enchaînez les combos et visez le meilleur score mondial dans ce jeu Android gratuit et open source.', skip:'Aller au contenu', navLabel:'Navigation principale', navGame:'Le jeu', navScores:'Scores', navPlay:'Jouer', language:'Langue', eyebrow:'Doigts rapides. Combos géants.', heroTitle:'Éclatez tout jusqu’au sommet.', heroLead:'Choisissez les bonnes couleurs, enchaînez des combos explosifs et transformez chaque partie intense en nouveau record.', download:'Télécharger le jeu', seeScores:'Voir le top 10', featuresLabel:'Points forts', seconds:'temps gagné ou perdu', combos:'multiplicateur de combo', topPlayers:'classement mondial', liveLabel:'En direct de l’arène', scoreTitle:'Top 10 mondial', refresh:'Actualiser', currentChampion:'Champion actuel', loading:'Chargement du classement…', empty:'Aucun score. Devenez le premier champion !', error:'Le classement fait une pause. Réessayez bientôt.', points:'pts', inAction:'Le jeu en action', showcaseTitle:'Facile à lancer. Difficile à quitter.', ready:'Prêt ?', ctaTitle:'Votre nom mérite la première place.', ctaText:'Gratuit, open source et parfait pour une partie rapide.', privacy:'Confidentialité'},
  ja: {...english, name:'日本語', locale:'ja-JP', title:'Bubble Penetration – 爽快バブルアーケードゲーム', description:'正しいバブルを狙い、コンボをつないで世界ハイスコアを目指す、無料のオープンソースAndroidゲーム。', skip:'本文へ移動', navLabel:'メインナビゲーション', navGame:'ゲーム', navScores:'ハイスコア', navPlay:'今すぐプレイ', language:'言語', eyebrow:'素早い指。大きなコンボ。', heroTitle:'弾けて、頂点へ。', heroLead:'正しい色を選び、豪快なコンボをつないで、熱い一戦を自己ベストに変えよう。', download:'ゲームをダウンロード', seeScores:'トップ10を見る', featuresLabel:'ゲームの特徴', seconds:'時間が増減', combos:'コンボ倍率', topPlayers:'世界ランキング', liveLabel:'アリーナからライブ', scoreTitle:'世界トップ10', refresh:'更新', currentChampion:'現在のチャンピオン', loading:'ランキングを読み込み中…', empty:'まだスコアがありません。最初の王者になろう！', error:'ランキングを取得できません。しばらくして再試行してください。', points:'点', inAction:'ゲームプレイ', showcaseTitle:'すぐ遊べて、やめられない。', ready:'準備はいい？', ctaTitle:'頂点に君の名前を。', ctaText:'無料・オープンソース。短時間で楽しめます。', privacy:'プライバシー'},
  'pt-BR': {...english, name:'Português (Brasil)', locale:'pt-BR', title:'Bubble Penetration – Jogo arcade rápido de bolhas', description:'Estoure as bolhas certas, faça combos e dispute a maior pontuação global neste jogo Android gratuito e de código aberto.', skip:'Ir para o conteúdo', navLabel:'Navegação principal', navGame:'O jogo', navScores:'Pontuações', navPlay:'Jogar agora', language:'Idioma', eyebrow:'Dedos rápidos. Combos enormes.', heroTitle:'Estoure tudo até o topo.', heroLead:'Escolha as cores certas, encaixe combos explosivos e transforme cada rodada frenética em seu novo recorde.', download:'Baixar o jogo', seeScores:'Ver o top 10', featuresLabel:'Destaques do jogo', seconds:'tempo ganho ou perdido', combos:'multiplicador de combo', topPlayers:'ranking global', liveLabel:'Ao vivo da arena', scoreTitle:'Top 10 global', refresh:'Atualizar', currentChampion:'Campeão atual', loading:'Carregando o ranking…', empty:'Ainda não há pontuações. Seja o primeiro campeão!', error:'O ranking está descansando. Tente novamente em breve.', points:'pts', inAction:'O jogo em ação', showcaseTitle:'Fácil de começar. Difícil de parar.', ready:'Pronto?', ctaTitle:'Seu nome merece o topo.', ctaText:'Grátis, de código aberto e feito para diversão rápida.', privacy:'Privacidade'},
  ru: {...english, name:'Русский', locale:'ru-RU', title:'Bubble Penetration – Динамичная аркада с пузырями', description:'Лопайте нужные пузыри, собирайте комбо и боритесь за мировой рекорд в бесплатной Android-игре с открытым кодом.', skip:'Перейти к содержанию', navLabel:'Главная навигация', navGame:'Игра', navScores:'Рекорды', navPlay:'Играть', language:'Язык', eyebrow:'Быстрые пальцы. Огромные комбо.', heroTitle:'Лопай и покоряй вершину.', heroLead:'Выбирайте правильные цвета, собирайте взрывные комбо и превращайте каждый безумный раунд в новый рекорд.', download:'Скачать игру', seeScores:'Смотреть топ-10', featuresLabel:'Особенности игры', seconds:'время растёт и уменьшается', combos:'множитель комбо', topPlayers:'мировой рейтинг', liveLabel:'Прямо с арены', scoreTitle:'Мировой топ-10', refresh:'Обновить', currentChampion:'Текущий чемпион', loading:'Загрузка рейтинга…', empty:'Рекордов пока нет. Станьте первым чемпионом!', error:'Рейтинг временно недоступен. Попробуйте позже.', points:'очк.', inAction:'Игра в действии', showcaseTitle:'Легко начать. Трудно остановиться.', ready:'Готовы?', ctaTitle:'Ваше имя должно быть наверху.', ctaText:'Бесплатно, открыто и идеально для быстрой игры.', privacy:'Конфиденциальность'},
  uk: {...english, name:'Українська', locale:'uk-UA', title:'Bubble Penetration – Динамічна аркада з бульбашками', description:'Лускайте правильні бульбашки, складайте комбо та боріться за світовий рекорд у безкоштовній Android-грі з відкритим кодом.', skip:'Перейти до вмісту', navLabel:'Головна навігація', navGame:'Гра', navScores:'Рекорди', navPlay:'Грати', language:'Мова', eyebrow:'Швидкі пальці. Великі комбо.', heroTitle:'Лускай і підкорюй вершину.', heroLead:'Обирайте правильні кольори, складайте вибухові комбо та перетворюйте кожен шалений раунд на новий рекорд.', download:'Завантажити гру', seeScores:'Дивитися топ-10', featuresLabel:'Особливості гри', seconds:'час додається й віднімається', combos:'множник комбо', topPlayers:'світовий рейтинг', liveLabel:'Наживо з арени', scoreTitle:'Світовий топ-10', refresh:'Оновити', currentChampion:'Поточний чемпіон', loading:'Завантаження рейтингу…', empty:'Рекордів ще немає. Станьте першим чемпіоном!', error:'Рейтинг тимчасово недоступний. Спробуйте пізніше.', points:'очк.', inAction:'Гра в дії', showcaseTitle:'Легко почати. Важко зупинитися.', ready:'Готові?', ctaTitle:'Ваше ім’я має бути нагорі.', ctaText:'Безкоштовно, відкрито та ідеально для швидкої гри.', privacy:'Конфіденційність'},
  'zh-CN': {...english, name:'简体中文', locale:'zh-CN', title:'Bubble Penetration – 快节奏泡泡街机游戏', description:'击中正确的泡泡，连续触发组合，在这款免费开源的 Android 街机游戏中争夺全球最高分。', skip:'跳到主要内容', navLabel:'主导航', navGame:'游戏', navScores:'最高分', navPlay:'立即游玩', language:'语言', eyebrow:'手速要快。连击要大。', heroTitle:'一路爆破，冲上榜首。', heroLead:'选择正确颜色，触发爆炸连击，把每一局刺激挑战变成你的全新纪录。', download:'下载游戏', seeScores:'查看前10名', featuresLabel:'游戏亮点', seconds:'时间增减', combos:'连击倍数', topPlayers:'全球排行榜', liveLabel:'竞技场实时数据', scoreTitle:'全球前10名', refresh:'刷新', currentChampion:'当前冠军', loading:'正在加载排行榜…', empty:'暂无分数。成为第一位冠军吧！', error:'排行榜暂时休息，请稍后重试。', points:'分', inAction:'游戏实机画面', showcaseTitle:'上手简单，根本停不下来。', ready:'准备好了吗？', ctaTitle:'榜首就差你的名字。', ctaText:'免费、开源，随时享受快节奏乐趣。', privacy:'隐私'}
};

Object.assign(translations.es, { seconds:'combo máximo', combos:'tiempo y puntos extra', topPlayers:'online, propia u offline' });
Object.assign(translations.fr, { seconds:'combo maximal', combos:'temps et points bonus', topPlayers:'en ligne, personnalisé ou hors ligne' });
Object.assign(translations.ja, { seconds:'最大コンボ', combos:'ボーナス時間＆スコア', topPlayers:'オンライン・独自・オフライン' });
Object.assign(translations['pt-BR'], { seconds:'combo máximo', combos:'tempo e pontos extras', topPlayers:'online, próprio ou offline' });
Object.assign(translations.ru, { seconds:'максимальное комбо', combos:'бонус времени и очков', topPlayers:'онлайн, свой или офлайн' });
Object.assign(translations.uk, { seconds:'максимальне комбо', combos:'бонус часу й очок', topPlayers:'онлайн, власний або офлайн' });
Object.assign(translations['zh-CN'], { seconds:'最高连击', combos:'额外时间与分数', topPlayers:'在线、自定义或离线' });

Object.assign(translations.de, { howLabel:'So funktioniert es', howTitle:'Jeder Tipp verändert die Runde.', colorTitle:'Folge der Farbe', colorText:'Sammle die aktuell geforderte Farbe, um Punkte und wertvolle Zeit zu gewinnen.', starTitle:'Schnapp dir goldene Sterne', starText:'Sterne belohnen schnelle Reaktionen mit Bonuszeit und Extrapunkten.', comboTitle:'Halte deine Serie', comboText:'Richtige Treffer steigern den Multiplikator bis ×16. Eine falsche Blase kostet Zeit und beendet die Combo.' });
Object.assign(translations.es, { howLabel:'Cómo funciona', howTitle:'Cada toque cambia la partida.', colorTitle:'Sigue el color', colorText:'Recoge el color indicado para ganar puntos y tiempo.', starTitle:'Atrapa estrellas doradas', starText:'Las estrellas dan tiempo adicional y puntos extra.', comboTitle:'Mantén la racha', comboText:'Los aciertos aumentan el multiplicador hasta ×16. Un error cuesta tiempo y reinicia el combo.' });
Object.assign(translations.fr, { howLabel:'Comment jouer', howTitle:'Chaque toucher change la partie.', colorTitle:'Suivez la couleur', colorText:'Collectez la couleur demandée pour gagner des points et du temps.', starTitle:'Attrapez les étoiles', starText:'Les étoiles offrent du temps bonus et des points supplémentaires.', comboTitle:'Gardez votre série', comboText:'Les bons choix montent le multiplicateur jusqu’à ×16. Une erreur coûte du temps et réinitialise le combo.' });
Object.assign(translations.ja, { howLabel:'遊び方', howTitle:'タップするたびに展開が変わる。', colorTitle:'指定の色を狙う', colorText:'現在指定されている色を集めて、スコアと貴重な時間を獲得。', starTitle:'金色の星をゲット', starText:'星を取るとボーナス時間と追加スコアを獲得。', comboTitle:'連続ヒットを守る', comboText:'正解を重ねると最大×16。間違えると時間を失い、コンボがリセット。' });
Object.assign(translations['pt-BR'], { howLabel:'Como jogar', howTitle:'Cada toque muda a rodada.', colorTitle:'Siga a cor', colorText:'Colete a cor indicada para ganhar pontos e tempo.', starTitle:'Pegue estrelas douradas', starText:'Estrelas dão tempo bônus e pontos extras.', comboTitle:'Mantenha a sequência', comboText:'Acertos aumentam o multiplicador até ×16. Um erro custa tempo e reinicia o combo.' });
Object.assign(translations.ru, { howLabel:'Как играть', howTitle:'Каждое нажатие меняет раунд.', colorTitle:'Следуйте цвету', colorText:'Собирайте нужный цвет, чтобы получить очки и время.', starTitle:'Ловите золотые звёзды', starText:'Звёзды дают бонусное время и дополнительные очки.', comboTitle:'Сохраняйте серию', comboText:'Верные попадания повышают множитель до ×16. Ошибка отнимает время и сбрасывает комбо.' });
Object.assign(translations.uk, { howLabel:'Як грати', howTitle:'Кожен дотик змінює раунд.', colorTitle:'Стежте за кольором', colorText:'Збирайте потрібний колір, щоб отримати очки й час.', starTitle:'Ловіть золоті зірки', starText:'Зірки дають бонусний час і додаткові очки.', comboTitle:'Тримайте серію', comboText:'Влучання підвищують множник до ×16. Помилка забирає час і скидає комбо.' });
Object.assign(translations['zh-CN'], { howLabel:'玩法', howTitle:'每次点击都会改变战局。', colorTitle:'跟随指定颜色', colorText:'收集当前指定的颜色，获得分数和宝贵时间。', starTitle:'抓住金色星星', starText:'星星会奖励额外时间和附加分数。', comboTitle:'保持连续命中', comboText:'正确点击可将倍数提升至×16。点错会损失时间并重置连击。' });

Object.assign(translations.de, { download:'Spiel (APK) herunterladen', storeLabel:'Spiel beziehen', getItOn:'Erhältlich bei', comingSoon:'Demnächst' });
Object.assign(translations.es, { download:'Descargar juego (APK)', storeLabel:'Conseguir el juego', getItOn:'Disponible en', comingSoon:'Próximamente' });
Object.assign(translations.fr, { download:'Télécharger le jeu (APK)', storeLabel:'Obtenir le jeu', getItOn:'Disponible sur', comingSoon:'Bientôt disponible' });
Object.assign(translations.ja, { download:'ゲーム（APK）をダウンロード', storeLabel:'ゲームを入手', getItOn:'入手先', comingSoon:'近日公開' });
Object.assign(translations['pt-BR'], { download:'Baixar jogo (APK)', storeLabel:'Baixar o jogo', getItOn:'Disponível no', comingSoon:'Em breve' });
Object.assign(translations.ru, { download:'Скачать игру (APK)', storeLabel:'Получить игру', getItOn:'Доступно в', comingSoon:'Скоро' });
Object.assign(translations.uk, { download:'Завантажити гру (APK)', storeLabel:'Отримати гру', getItOn:'Доступно в', comingSoon:'Незабаром' });
Object.assign(translations['zh-CN'], { download:'下载游戏（APK）', storeLabel:'获取游戏', getItOn:'下载自', comingSoon:'即将推出' });
