import { describe, expect, it } from '@jest/globals';
import { BadRequestException } from '@nestjs/common';
import { UsernameValidationService } from './username-validation.service';

describe('UsernameValidationService', () => {
  const service = new UsernameValidationService();

  it.each(['!!!', ',,,,', '...', '184583023', '😄'])(
    'rejects a username without letters: %s',
    async (username) => {
      await expect(service.validate(username)).rejects.toThrow(
        BadRequestException,
      );
    },
  );

  it.each([
    'BubbleFan! ❤️',
    'Sternenfunke',
    'Wolkenpfad',
    'Kometenflug',
    'Mondschein',
    'Nebelwald',
    'Regenbogen',
    'Sonnenstrahl',
    'Kristallsee',
    'Funkelstein',
    'Abendwind',
    'StarGlimmer',
    'CloudTrail',
    'CometDash',
    'Moonlight',
    'MistForest',
    'RainbowSky',
    'Sunbeam',
    'CrystalLake',
    'SparkStone',
    'EveningWind',
    'RayoClaro',
    'LunaAzul',
    'BrisaSuave',
    'CieloVivo',
    'BosqueNiebla',
    'SolDorado',
    'MarCalmo',
    'EstrellaFiel',
    'NubeVeloz',
    'RioBrillante',
    'LuneClaire',
    'EtoileVive',
    'BriseDouce',
    'CielBleu',
    'ForetBrume',
    'SoleilOr',
    'MerCalme',
    'NuageRapide',
    'RiviereClair',
    'PierreEtincelle',
    '月光',
    '星旅',
    '青空',
    '虹風',
    '海音',
    '雲道',
    '花火',
    '光輪',
    '雪兎',
    '夜空',
    'LuaClara',
    'EstrelaViva',
    'BrisaLeve',
    'CeuAzul',
    'FlorestaNeblina',
    'SolDourado',
    'MarCalmo',
    'NuvemRapida',
    'RioBrilhante',
    'PedraLuz',
    'ЛунныйЛуч',
    'ЗвёздныйПуть',
    'ТихийВетер',
    'СинееНебо',
    'ЛеснойТуман',
    'ЗолотоеСолнце',
    'СпокойноеМоре',
    'БыстроеОблако',
    'ЯркаяРека',
    'ИскраКамня',
    'МісячнийПромінь',
    'ЗорянийШлях',
    'ТихийВітер',
    'СинєНебо',
    'ЛісовийТуман',
    'ЗолотеСонце',
    'СпокійнеМоре',
    'ШвидкаХмара',
    'ЯскраваРічка',
    'ІскраКаменю',
    '月光',
    '星旅',
    '青空',
    '虹風',
    '海音',
    '雲道',
    '花火',
    '光輪',
    '雪兎',
    '夜空',
  ])('accepts the clean username %s', async (username) => {
    await expect(service.validate(username)).resolves.toBeUndefined();
  });
});
